name: cari_atap
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.9.2







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  google_fonts: ^7.0.0
  gap: ^3.0.1
  get: ^4.7.3
  http: ^1.6.0
  intl: ^0.20.2
  carousel_slider: ^5.1.1
  shared_preferences: ^2.5.4
  json_annotation: ^4.10.0
  dio: ^5.9.1
  crystal_navigation_bar: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
